# Generated by Django 4.1.6 on 2023-03-01 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0010_orderedcourse_delete_ordered_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=20)),
                ('end_date', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_batch', to='course.course')),
                ('participants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_batch', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
