# Generated by Django 4.1.6 on 2023-03-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingbatch',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='trainingbatch',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
