# Generated by Django 4.1.6 on 2023-03-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_registerbatch'),
        ('customadmin', '0005_remove_trainingbatch_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingbatch',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to='course.registerbatch'),
        ),
    ]
