# Generated by Django 4.1.6 on 2023-03-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_registerbatch'),
        ('customadmin', '0006_alter_trainingbatch_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingbatch',
            name='participants',
            field=models.ManyToManyField(blank=True, to='course.registerbatch'),
        ),
    ]
