# Generated by Django 4.1.6 on 2023-03-02 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_registerbatch_end_date_registerbatch_start_date'),
        ('customadmin', '0007_alter_trainingbatch_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingbatch',
            name='participants',
        ),
        migrations.AddField(
            model_name='trainingbatch',
            name='participants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.registerbatch'),
        ),
    ]
