# Generated by Django 4.1.7 on 2023-03-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_registerbatch_end_date_registerbatch_start_date'),
        ('customadmin', '0008_remove_trainingbatch_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingbatch',
            name='participants',
        ),
        migrations.AddField(
            model_name='trainingbatch',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to='course.registerbatch'),
        ),
    ]
