# Generated by Django 4.1.7 on 2023-03-03 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customadmin', '0009_remove_trainingbatch_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingbatch',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
