# Generated by Django 4.1.7 on 2023-03-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_remove_registerbatch_end_date_and_more'),
        ('customadmin', '0010_alter_trainingbatch_participants'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingbatch',
            unique_together={('course',)},
        ),
    ]
