# Generated by Django 4.1.7 on 2023-03-06 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0011_alter_trainingbatch_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingbatch',
            unique_together=set(),
        ),
    ]
