# Generated by Django 4.1.6 on 2023-02-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_custom_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
