# Generated by Django 4.1.6 on 2023-02-21 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_category_courses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='courses',
            new_name='Course',
        ),
    ]
