# Generated by Django 4.1.6 on 2023-02-21 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_courses_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
