# Generated by Django 4.1.6 on 2023-02-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_ordered_course_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered_course',
            name='course',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordered_course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
