# Generated by Django 4.1.6 on 2023-02-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_ordered_course_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered_course',
            name='status',
            field=models.CharField(choices=[('Processing', 'Paid'), ('Completed', 'Cancelled')], default='Processing', max_length=20),
        ),
    ]
