# Generated by Django 4.1.6 on 2023-02-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_ordered_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered_course',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='Processing', max_length=20),
        ),
    ]
