# Generated by Django 4.1.7 on 2023-02-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_orderedcourse_delete_ordered_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedcourse',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
