# Generated by Django 4.1.6 on 2023-03-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_registerbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerbatch',
            name='course',
            field=models.CharField(max_length=255),
        ),
    ]
