# Generated by Django 4.1.7 on 2023-02-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_orderedcourse_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedcourse',
            name='proof_of_payment',
            field=models.ImageField(upload_to='payment_images/'),
        ),
    ]
