# Generated by Django 4.1.6 on 2023-03-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_registerbatch_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerbatch',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registerbatch',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
