# Generated by Django 4.1.7 on 2023-03-06 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0014_remove_registerbatch_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerbatch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_batch', to='course.course'),
        ),
        migrations.AlterUniqueTogether(
            name='registerbatch',
            unique_together={('user', 'course')},
        ),
    ]
