# Generated by Django 4.1.7 on 2023-03-06 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_registerbatch_course_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registerbatch',
            unique_together={('batch_course_id',)},
        ),
    ]
